platform :ios, '7.0'
target :TimeKiller do
pod "AFNetworking", "~> 3.0"
pod 'SDWebImage'
pod 'MJRefresh'
pod 'FMDB'
pod 'Masonry'
pod ‘MBProgressHUD','~>0.9.2'
pod 'RDVTabBarController'
pod "MWPhotoBrowser"
end
